### ISSUE TITLE
Android offline version?

### ISSUE THREAD

**Issue by Maybe-Anton** [jonathansfox/lcs-new-age#16]
Hello, I would like to know if there is an offline version for Android planned.

**Comment by jonathansfox** [comment]
Yes, in fact, you should be able to install the game for offline use now, actually!

The way to do this is by opening it in your preferred web browser, then choosing "install" or "add to home screen" (the language may vary by browser). This will either be something offered near the bottom of your screen, or you might need to find it in a menu--the "three dots" menu or "share" icon may be where it's hiding.

When you add the web page to your home screen, all the necessary files to run the game offline will also be installed to your phone or tablet. Under the hood, that browser will technically still be responsible for running the game--and the game will still ping my website to check for updates when you first open it, if you're online--but if you _aren't_ online, instead of giving you an error because it can't reach the website, it will go ahead and run the game offline on your phone or tablet using the files it downloaded earlier.

Let me know if you have any trouble with this!

**Comment by jonathansfox** [comment]
Advanced answer, if you really want a native APK instead of an offline-installed PWA (progressive web app):

While I'm not personally planning to make an APK, LCS:NA was built on the Flutter framework which was originally designed to build native mobile apps, not web pages. So it should be very possible! You have my blessing if you want to make a small project of grabbing the source code and building an APK yourself; I just haven't actually tested this and don't currently plan to, so you might need to make some changes to dependencies or fix some bugs. Or maybe it'll work right away out of the box, I don't know.

**Comment by Maybe-Anton** [comment]
Unfortunately I'm quite bad at programming, to be honest I tried to make the older port of liberal crime squad work a few days ago which was made quite a long time ago, unfortunately it didn't work and I lost hope of trying to make it work. When I saw that your version works in the browser I was like "hey these dudes made this game work in the browser and maybe they can make an offline version for phones?" and because of that I'm writing to you.

**Comment by jonathansfox** [comment]
No worries then, the first option is always there! In Chrome for Android, you can open the game, then press the browser's three dots menu ("More") in the corner, then "Add to home screen" in that menu, and then confirm with the "Install" button. That will package the game up as a locally installed app on your device that still runs on Chrome under the hood, but doesn't require a connection to the internet to work.

**Comment by Maybe-Anton** [comment]
Oh, I forgot to say, but this option didn't work

**Comment by jonathansfox** [comment]
Can you tell me what didn't work? This is supported behavior so if it's not working it's a bug and I want to fix it.

**Comment by Maybe-Anton** [comment]
The problem is not with the game, but with the browser, which refuses to work without an internet connection.

**Comment by jonathansfox** [comment]
Hm, okay. I blew the dust off of a Galaxy Tab A I had in a box somewhere to test this on my end too, and it gave me a blank white page when launching the game offline via Chrome (after a briefly displayed message about being offline). That _isn't_ how it's supposed to work, and means I might have set something up wrong when adding support for installing offline.

I know I've tested this offline and confirmed it was working offline on iOS and Desktop, but that was a long time ago.... and until now, I never tested it specifically on Android. So maybe it broke at some point, or maybe it was never working like it was supposed to on Android. Either way, thank you for your report! I'll look into this more. This is definitely a feature I care about working, since one my goals with this was to have a version that works on Android and iOS, including offline.

So I guess I need to revise my answer to your question: Yes, I am planning to add the ability to install for Android offline. I mistakenly thought it was already working, and now I need to investigate why it isn't.

**Comment by jonathansfox** [comment]
Working on this. I've identified the root cause of the game not running offline anymore, and I've tested a fix and the fix seems to be working. Awkwardly, it looks like the least brittle way to resolve this is going to involve moving the game to a subdomain instead of its current location.

I still need to do a couple things before I can make a new build that fixes this bug:
- Verify that existing PWA installs will continue to work if I create a permanent redirect to move the latest content to a new location
- Finish some in-progress content changes (in particular, the addition of the Housing, Healthcare, and Retirement issues, and corresponding content)

**Comment by ashley-s-fox** [comment]
I believe this is now fixed in the latest update. Finally.

It definitely took me a while to get an update out after identifying the fix for this; apologies for that.

**Comment by Morinn69** [comment]
**Nope**. Still not working. 

To replicate: open the 'app' without internet connection. Google Chrome, Android 15.

**Comment by ashley-s-fox** [comment]
Just noting for posterity: It was fixed for three days. And then I updated the Flutter framework and it immediately broke again.

It's now fixed again, with an update to my build process to give me early warning if this ever happens again.
